CREATE TABLE crate(
  CRATE_ID       BIGINT AUTO_INCREMENT,
  NAME              VARCHAR(250),
  STATUS            VARCHAR(100),
  CREATED_DATE      DATETIME,
  CREATED_BY        VARCHAR(25),
  LAST_UPDATE_DATE  DATETIME,
  LAST_UPDATE_BY    VARCHAR(25),
  PRIMARY KEY (CRATE_ID)
);

CREATE TABLE dog (
  DOG_ID            BIGINT AUTO_INCREMENT,
  NAME              VARCHAR(250),
  WEIGHT            DOUBLE,
  INTELLIGENCE      VARCHAR(100),
  SHEDDING          VARCHAR(100),
  CRATE_ID          BIGINT,
  CREATED_DATE      DATETIME,
  CREATED_BY        VARCHAR(25),
  LAST_UPDATE_DATE  DATETIME,
  LAST_UPDATE_BY    VARCHAR(25),
  PRIMARY KEY (DOG_ID),
  CONSTRAINT FK_CRATE FOREIGN KEY (CRATE_ID) REFERENCES crate(CRATE_ID)
);